### PR TITLE
link-libraries: convert the link-libraries test into a multi-arch rea…

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
…dy environment.

This fixes installation failures e.g. on Ubuntu i686, because it is only multi-arch on top of x64 chroot.
Also, try to run the built binary, but it fails because of code trying to dereference NULL

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
Hello @kilobyte sadly I couldn't also run the test... because e.g.
daxctl_dev_get_id(0)
means
*0->id;

and this crashes :)
Also creating a fake struct with a fake id doesn't work because such struct is defined in a private header.
Copy-pasting struct is not error prone on new upstream releases (with ABI breakages), and I coulnd't find some example working test online.
However I really hope you can accept this improvement that is easily extensible, works in multi-arch, uses pkg-config to detect libraries and so on...

**Comment by kilobyte** [comment]
Well, the point of that test was to check whether headers and runtime libs are in the right place (something that I didn't trust upon upstream's change of build systems), and the easy way to do so is to take random symbols and not bother with their arguments, like eg. autotools' configure does.

Actually crafting a working example would require some effort, that's why I decided against :p

**Comment by kilobyte** [comment]
Hmm... is there any case where autopkgtests are run during a cross-compilation?

**Comment by LocutusOfBorg** [comment]
Hello, yes, in Ubuntu for example, i386 is not a real architecture anymore, we just build a subset of libraries there, and we run stuff on top of amd64 chroot.
Maybe, one day, also Debian might take a similar approach, because 32bit as "host" is fortunately dying ;)

**Comment by kilobyte** [comment]
Running test this way seems weird to me, and this complexity is useless in Debian.
But if it makes your work in Ubuntu easier, 'ere you go!

**Comment by LocutusOfBorg** [comment]
Hello @kilobyte, thanks for merging, but may I ask why do you think its useless? 
This new test is easily extendible, e.g. in case the library changes the link name, or adds some link dependency it will continue to work, because pkg-config will add them correctly.
Also, we can now (in case we fix the segfault) try to run the resulting binary and fail if it doesn't return correctly.
I think its a better test w.r.t. the previous version. And maybe in the future this will be even more "visible"

**Pull request merged**
